#!/usr/bin/env ruby
# frozen_string_literal: true
# encoding: UTF-8
# (c) ANB Andrew Bizyaev

module PhTools
  tool_name = File.basename(__FILE__)
  require tool_name.to_s

  file_type = FILE_TYPE_IMAGE + FILE_TYPE_VIDEO + FILE_TYPE_AUDIO
  usage = <<DOCOPT
***************************************************
phtools - *Keep Your Photos In Order* (c) ANB
***************************************************
#{tool_name} copies the input file to backup directory.
Optimized to be used with other *phtools* via pipes.
Example: phls | #{tool_name} | phrename ...

Usage:
  #{tool_name} [--backup DIR] [-D]
  #{tool_name} -h | --help
  #{tool_name} -v | --version

Options:
  -b DIR --backup=DIR  Sets the backup directory [Default: ./backup]
  -D --debug           Turn on debugging (verbose) mode
  -h --help            Show this screen.
  -v --version         Show version.
DOCOPT

  PhTools.const_get(tool_name.capitalize).new(usage, file_type).run!
end
