#!/usr/bin/env ruby
# encoding: UTF-8
# (c) ANB Andrew Bizyaev

module PhTools
  tool_name = File.basename(__FILE__)
  require "#{tool_name}"

  file_type = FILE_TYPE_IMAGE + FILE_TYPE_VIDEO + FILE_TYPE_AUDIO
  usage = <<DOCOPT
***************************************************
phtools - *Keep Your Photos In Order* (c) ANB
***************************************************
#{tool_name} scans given directories and generates list of files to standard output.
In short it acts like a smart 'ls' command (or 'dir' in Windows).
Set DIRs to be scanned as a parameters. If no DIRs are set - current dir (.)
will be scanned. Set FILEMASKs as a parameters - and only files matching the
masks will be processed. If no FILEMASK is set *.* will be used by-default.
To avoid unnessesary mask extraction by OS - put it in ''.
Note, #{tool_name} works only with phtools-friendly file types: #{file_type * ','}
#{tool_name} is a starting point for all other phtools to be connected via pipes.

Example: #{tool_name} abc '*aaa*' | phrename -a anb => scans 'abc' folder and
sends all found phtools friendly files filtered with *aaa* to phrename command.

Usage:
  #{tool_name} [-D] [-r] [DIR_OR_FILEMASK...]
  #{tool_name} -h | --help
  #{tool_name} -v | --version

Options:
  -D --debug      Turn on debugging (verbose) mode
  -r --recursive  Recursively scan directories
  -h --help       Show this screen.
  -v --version    Show version.
DOCOPT

  PhTools.const_get(tool_name.capitalize).new(usage, file_type).run!
end
