#!/usr/bin/env ruby
# encoding: UTF-8
# (c) ANB Andrew Bizyaev

module PhTools
  tool_name = File.basename(__FILE__)
  require "#{tool_name}"

  file_type = FILE_TYPE_IMAGE + FILE_TYPE_VIDEO + FILE_TYPE_AUDIO
  usage = <<DOCOPT
***************************************************
phtools - *Keep Your Photos In Order* (c) ANB
***************************************************
#{tool_name} moves input file(s) into WORKING_FOLDER
separating photo files, RAW photo files and VIDEO files in corresponding
subfolders.
phtools friendly files: #{file_type * ','}

Optimized to be used with other *phtools* via pipes.
Example: phls | phrename -a anb | #{tool_name}

Usage:
  #{tool_name} [-w WORKING_FOLDER] [-D]
  #{tool_name} -h | --help
  #{tool_name} -v | --version

Options:
  -w FLD --working_folder=FLD  Folder the input files to be
                               moved to [default: .]
  -D --debug    Turn on debugging (verbose) mode
  -h --help     Show this screen.
  -v --version  Show version.
DOCOPT

  PhTools.const_get(tool_name.capitalize).new(usage, file_type).run!
end
