#!/usr/bin/env ruby
# encoding: UTF-8
# (c) ANB Andrew Bizyaev

module PhTools
  tool_name = File.basename(__FILE__)
  require "#{tool_name}"

  file_type = FILE_TYPE_IMAGE + FILE_TYPE_VIDEO + FILE_TYPE_AUDIO
  usage = <<DOCOPT
***************************************************
phtools - *Keep Your Photos In Order* (c) ANB
***************************************************
#{tool_name} renames the input files based on EXIF
DateTimeOriginal (or CreateDate) tag and author NICKNAME provided.
The target file name format is YYYYmmdd-HHMMSS_AAA ORIGINAL.EXT, where:
  YYYYmmdd-HHMMSS - Date-Time of photo creation (DateTimeOriginal tag),
  AAA - the author nickname,
  ORIGINAL.EXT - the photo name given by digital camera.
Input file should be one of the types: #{file_type * ','}
Example: input file DSC03455.JPG will be renamed to 20130108-124145_ANB DSC03455.JPG
#{tool_name} is optimized to be used with other *phtools* via pipes, e.g.:
  phls | #{tool_name} -a anb

This program uses external utility ExifTool by Phil Harvey
(http://www.sno.phy.queensu.ca/~phil/exiftool/).

Usage:
  #{tool_name} -a NICK [-D] [-t TAG]
  #{tool_name} -c [-D]
  #{tool_name} -s DELTA [-D]
  #{tool_name} -h | --help
  #{tool_name} -v | --version

Options:
  -a NICK --author=NICK  Author nickname size should be #{PhFile::NICKNAME_SIZE} chars,
                         supports only latin ASCII chars (e.g. ANB).
                         No digits, no spaces, no other non-word chars allowed.

  -t TAG --tag_date=TAG  Set the TAG name containing Date_Time creation
                         info. The TAG value will be used instead of
                         standard DateTimeOriginal tag. All existing tags you
                         can get using command `phls filename|phmtags -f`

  -c --clean             Rename file(s) back to original name(s)

  -s DELTA --shift_time=DELTA  DELTA (in seconds) will be added to Date-Time value
                         of the filename. If DELTA is positive the photo
                         will become yonger: e.g. 20140720-100005, DELTA = 65
                         result = 20140720-100110. In DELTA is negative the photo
                         will get DELTA seconds older.

  -D --debug    Turn on debugging (verbose) mode
  -h --help     Show this screen.
  -v --version  Show version.
DOCOPT

  PhTools.const_get(tool_name.capitalize).new(usage, file_type).run!
end
